version: 2
updates:
  # GitHub Actionsで使用するActionの自動バージョン更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "security"
